import { createClient } from "@/app/lib/supabase/server";
import AdminForms from "./AdminForms";

export default async function AdminPage() {
  const supabase = await createClient();
  const [{ data: accounts }, { data: profiles }, { data: ledger }] = await Promise.all([
    supabase.from("investor_accounts").select("id, account_code, status, user_id").order("created_at", { ascending: false }),
    supabase.from("profiles").select("id, full_name, role").eq("role", "investor"),
    supabase.from("ledger_entries").select("id, account_id, entry_type, amount, effective_at, reference, notes").order("effective_at", { ascending: false }),
  ]);
  const investorIds = new Set((profiles ?? []).map((profile) => profile.id));
  const names = new Map((profiles ?? []).map((profile) => [profile.id, profile.full_name]));
  const accountOptions = (accounts ?? []).filter((account) => investorIds.has(account.user_id)).map((account) => ({ ...account, partnerName: names.get(account.user_id) || "Unnamed partner" }));
  const partnerAccounts = (accounts ?? []).filter((account) => investorIds.has(account.user_id));
  const accountNames = new Map(partnerAccounts.map((account) => [account.id, names.get(account.user_id) || "Unnamed partner"]));
  const entries = ledger ?? [];
  const total = (type: string) => entries.filter((entry) => entry.entry_type === type).reduce((sum, entry) => sum + Number(entry.amount), 0);
  const currentCapital = total("contribution") + total("return") + total("adjustment") - total("withdrawal");
  const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
  return <div className="space-y-10"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-amber-300">Operations center</p><h1 className="mt-2 text-4xl font-semibold text-white">Admin dashboard</h1><p className="mt-2 max-w-2xl text-slate-400">Monitor partner capital, post approved movements, and keep every account activity traceable.</p></div><div className="rounded-xl border border-amber-400/20 bg-amber-400/10 px-4 py-3 text-sm text-amber-100">Live ledger · {new Date().toLocaleDateString("en-IN")}</div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Partners" value={String(partnerAccounts.length)} /><Metric label="Current capital" value={money(currentCapital)} accent="text-white" /><Metric label="Contributions" value={money(total("contribution"))} /><Metric label="Monthly interest" value={money(total("return"))} accent="text-emerald-300" /><Metric label="Withdrawals" value={money(total("withdrawal"))} accent="text-rose-300" /></div><div className="grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><AdminForms accounts={accountOptions} /><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold text-white">Recent ledger activity</h2><p className="mt-1 text-sm text-slate-500">The same entries appear in each partner transaction history.</p></div><span className="rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-400">{entries.length} total</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase tracking-wider text-slate-500"><tr><th className="pb-3 pr-4">Partner</th><th className="pb-3 pr-4">Type</th><th className="pb-3 pr-4">Amount</th><th className="pb-3">Date</th></tr></thead><tbody className="divide-y divide-slate-800">{entries.slice(0, 8).map((entry) => <tr key={entry.id}><td className="py-4 pr-4 text-slate-200">{accountNames.get(entry.account_id) || "Unknown partner"}<span className="mt-1 block text-xs text-slate-500">{entry.reference}</span></td><td className={`py-4 pr-4 capitalize ${entry.entry_type === "withdrawal" ? "text-rose-300" : entry.entry_type === "return" ? "text-emerald-300" : "text-slate-300"}`}>{entry.entry_type === "return" ? "Monthly interest" : entry.entry_type}</td><td className="py-4 pr-4 text-slate-200">{entry.entry_type === "withdrawal" ? "-" : "+"}{money(Number(entry.amount))}</td><td className="py-4 text-slate-500">{new Date(entry.effective_at).toLocaleDateString("en-IN")}</td></tr>)}{entries.length === 0 && <tr><td colSpan={4} className="py-8 text-center text-slate-500">No ledger activity yet.</td></tr>}</tbody></table></div></section></div></div>;
}

function Metric({ label, value, accent = "text-amber-200" }: { label: string; value: string; accent?: string }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className={`mt-3 text-2xl font-semibold ${accent}`}>{value}</p></div>; }