import Link from "next/link";
import { requireUser } from "@/app/lib/auth";
import { getInvestorDashboard } from "@/app/lib/investor";
import LiveRefresh from "./LiveRefresh";

const money = (value: number, currency: string) => new Intl.NumberFormat("en-IN", { style: "currency", currency }).format(value);

export default async function InvestorPage() {
  const user = await requireUser();
  const dashboard = await getInvestorDashboard(user.id);
  if (!dashboard) return <div className="rounded-2xl border border-amber-500/30 bg-amber-500/10 p-8 text-amber-100"><h1 className="text-2xl font-semibold">Your account is being prepared</h1><p className="mt-2 text-sm text-amber-200/80">Your login is verified. An administrator needs to link your investor account before financial data can appear here.</p></div>;

  const { account } = dashboard;
  return <div className="space-y-10"><LiveRefresh accountId={account.id} /><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-400">Investor dashboard</p><h1 className="mt-2 text-4xl font-semibold text-white">Good to see you.</h1><p className="mt-2 text-slate-400">Account {account.account_code} · Updates appear as your records are approved.</p></div><span className="w-fit rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-emerald-300">{account.status}</span></div><div className="grid gap-4 md:grid-cols-3"><Metric label="Current account value" value={money(dashboard.currentValue, account.currency)} accent="text-white" /><Metric label="Contributed" value={money(dashboard.principal, account.currency)} /><Metric label="Returns earned" value={money(dashboard.returnsEarned, account.currency)} accent="text-emerald-300" /></div><div className="grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-white">Recent activity</h2><Link href="/investor/transactions" className="text-sm text-cyan-400 hover:text-cyan-300">View all</Link></div><div className="mt-5 divide-y divide-slate-800">{dashboard.entries.slice(0, 5).map((entry) => <div key={entry.id} className="flex items-center justify-between gap-4 py-4"><div><p className="capitalize text-sm font-medium text-slate-200">{entry.entry_type}</p><p className="text-xs text-slate-500">{new Date(entry.effective_at).toLocaleDateString("en-IN")} · {entry.reference}</p></div><span className={entry.entry_type === "withdrawal" ? "text-rose-300" : "text-emerald-300"}>{entry.entry_type === "withdrawal" ? "-" : "+"}{money(entry.amount, account.currency)}</span></div>)}{dashboard.entries.length === 0 && <p className="py-6 text-sm text-slate-500">No activity recorded yet.</p>}</div></section><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><h2 className="text-lg font-semibold text-white">Approved returns</h2><div className="mt-5 space-y-4">{dashboard.returns.slice(0, 4).map((item) => <div key={item.id} className="flex items-center justify-between border-b border-slate-800 pb-4"><div><p className="text-sm text-slate-200">{new Date(item.period_end).toLocaleDateString("en-IN", { month: "short", year: "numeric" })}</p><p className="text-xs text-slate-500">{item.return_rate ? `${item.return_rate}% recorded` : "Approved period"}</p></div><span className="text-sm font-semibold text-emerald-300">{money(item.return_amount, account.currency)}</span></div>)}{dashboard.returns.length === 0 && <p className="text-sm text-slate-500">Your approved monthly returns will appear here.</p>}</div></section></div></div>;
}

function Metric({ label, value, accent = "text-cyan-300" }: { label: string; value: string; accent?: string }) {
  return <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><p className="text-sm text-slate-500">{label}</p><p className={`mt-3 text-2xl font-semibold ${accent}`}>{value}</p></div>;
}